### ISSUE TITLE
Issue for exception (System.IndexOutOfRangeException)

### ISSUE THREAD

**Issue by janhebnes** [janhebnes/startlist.club#242]
```c#
2023-08-07 02:39:58,266Z ERROR [CFG_DEV] - AprsListener OnAprsPacketReceived
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Contains(T item)
   at NetTopologySuite.Index.Quadtree.NodeBase`1.Remove(Envelope itemEnv, T item)
   at NetTopologySuite.Index.Quadtree.NodeBase`1.Remove(Envelope itemEnv, T item)
   at NetTopologySuite.Index.Quadtree.NodeBase`1.Remove(Envelope itemEnv, T item)
   at Skyhop.FlightAnalysis.FlightContextFactory.Enqueue(IEnumerable`1 positionUpdates)
   at Skyhop.FlightAnalysis.FlightContextFactory.Enqueue(PositionUpdate positionUpdate)
   at FlightJournal.Web.Aprs.AprsListener.OnAprsPacketReceived(Object sender, PacketReceivedEventArgs e) in D:\a\startlist.club\startlist.club\FlightJournal.Web\Aprs\AprsListener.cs:line 100
``` 

**Link:** https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22:%221a421708-aaa3-47f8-b711-0e675e83197e%22,%22ResourceGroup%22:%22rg-startlist.club%22,%22Name%22:%22appi-startlist%22%7D/DataModel/%7B%22eventId%22:%22f1706e16-498a-11ee-94d1-000d3ab866ae%22,%22timestamp%22:%222023-09-02T12:18:32.2240725Z%22%7D

**Problem Id:** System.IndexOutOfRangeException at NetTopologySuite.Index.Quadtree.Root`1.InsertContained

**Exception Type:** System.IndexOutOfRangeException

**Method:** NetTopologySuite.Index.Quadtree.Root`1.InsertContained

**Outer Exception Type:** System.IndexOutOfRangeException

**Outer Exception Message:** System.IndexOutOfRangeException: Index was outside the bounds of the array.

**Outer Exception Method:** System.Collections.Generic.List`1.Add

**Comment by janhebnes** [comment]
Bliver håndteret i [FlightJournal.Web/Aprs/AprsListener.cs](https://github.com/janhebnes/startlist.club/pull/243/commits/623204d9bb521256749d243a2d3849656833c44b#diff-458da9743b4f9dfd28f38c1bde4cbc03885d899d1b34a6de57c98bc7c4a32df3) med en catch (IndexOutOfRangeException) på pull request #243
